---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  sources:
  - repoURL: 'https://helm.ngc.nvidia.com/nvidia'
    chart: gpu-operator
    targetRevision: 23.9.1
    helm:
      valueFiles:
      - $values/gpu-operator.yaml
  - repoURL: 'https://github.com/ccharest93/config-values.git'
    ref: values