---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 25.11.0
    helm:
      valueFiles:
      - $values/prometheus.yaml
  - repoURL: 'https://github.com/ccharest93/config-values.git'
    ref: values