---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volcano
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: volcano-system
  sources:
  - repoURL: 'https://volcano-sh.github.io/helm-charts'
    chart: volcano
    targetRevision: 1.8.2
